---
title: "Why nonprofits?"
date: "2022-09-06"
---

## Instructions

Write a 2-page paper (≈500 words) explaining why you are interested in nonprofit organizations. Draw on your personal history, values, experiences, and/or faith to explain your interest in nonprofits. Describe any thoughts or plans on work you would like to do in the future with nonprofits and any issues or causes that you're particularly interested in.

## Turning it in

Submit the paper as a Word document or a PDF to iCollege. Do not submit a link to a Google document—if you use Google Docs, export the document as a Word or PDF file first and submit that.

## Grading

I will grade this paper using a check system:

- ✔+: (*45 points (112.5%) in gradebook*) Paper shows phenomenal thought and engagement. I will not assign these often.
- ✔: (*40 points (100%) in gradebook*) Paper is thoughtful, well-written, and covers everything in the prompt. This is the expected level of performance.
- ✔−: (*20 points (50%) in gradebook*) Paper is hastily composed, too short, and/or only cursorily covers everything in the prompt. This grade signals that you need to improve in future assignments. I will hopefully not assign these often.

Notice that is essentially a pass/fail or completion-based system. I'm not grading your writing ability, I'm not counting the exact number of words you're writing. I'm looking for thoughtfulness and seriousness. That's all. Do good work and you'll get a ✓.
