---
title: "Diversity strategy"
date: "2022-11-14"
---

## Instructions

You will write a ≈1,000-word paper covering one topic. Use headings and subheadings in your document so that it is easy to follow.

### 1: Diversity, Inclusion, Accessibility, and Equity policy

**Part 1:**

As a team, develop a formal policy for your nonprofit that outlines its approach to diversity, inclusion, accessibility, and equity. [Bloomerang has a template for a small arts organization](https://bloomerang.co/resources/templates/diversity-inclusion-and-equity-policy-template/)—this can be a useful start and example (But don't directly copy it! Make this policy your own!). Do this in 400–500 words.

**Part 2:**

Having a policy on paper is nice, but policies can be easy to ignore in practice. Describe how you will implement this formal policy in your nonprofit. What structural changes will you make to the organization's bylaws, board requirements, staff training, and so on? How will you infuse it into the nonprofit's culture? Do this in ≈500 words


## Turning it in

Submit the paper as a Word document or a PDF to iCollege. Do not submit a link to a Google document—if you use Google Docs, export the document as a Word or PDF file first and submit that.

Since this is a team assignment, only one copy of the assignment needs to be submitted.


## Grading

I will grade this assignment using this rubric: [`blank_dei.xlsx`](/files/blank_dei.xlsx)

*(I'd highly recommend downloading the rubric and referencing it as you work on your assignment!)*
