---
title: "Pre-class check-in"
---

<div class="date-block bg-assignment text-white p-2 fake-date-block">
<p class="date">Due by noon on each Thursday before class</p>
</div>

To encourage attendance and preparation, I use an honor-system-based self-reporting system. Before coming to class, you'll need to fill out this pre-class check-in on iCollege:

1. Are you here in class today?
    - Yes (*0.5 points*)
    - No (*0 points*)
2. How much of today's reading did you finish?
    - 100% (*3 points*)
    - 75–99% (*2 points*)
    - 40–74% (*1 points*)
    - 0–39% (*0 points*)
3. How well did you read?
    - I was engaged and read carefully (*3 points*)
    - I was fairly engaged and read fairly carefully (*2 points*)
    - I skimmed it (*1 points*)
    - I didn't read it at all (*0 points*)
4. Written response paragraph (*5 points*)

You'll also need to submit a short written response paragraph as part of each pre-class check-in. These both (1) allow me to make sure the class is understanding the materials, and (2) allow you to come prepared for effective team work in class. 

The question you need to answer will be included after the list of readings for each class session. Written responses should be about a paragraph, or ≈150 words. That's fairly short: there are ≈250 words on a typical double-spaced page in Microsoft Word (500 when single-spaced). **I recommend typing your written response paragraph in a separate document and copying/pasting the response into iCollege instead of typing in iCollege directly.**

These pre-class check-ins are due by the beginning of class on Thursdays. 

Each check-in is worth 11.5 points. There are 24 possible pre-class check-ins, but **I will only count the 20 highest grades**. (Note that this is how I track attendance, and note that attendance is only worth 0.5 points—that's just so I can quickly see fractions in the gradebook).
